name: dotnet-ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.102"

      - name: Dotnet Info
        run: dotnet --info

      - name: Restore
        run: dotnet restore Metrix_to_Cockpit.sln

      - name: Build
        run: dotnet build Metrix_to_Cockpit.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Metrix_to_Cockpit.sln --configuration Release --no-build --verbosity minimal
